### PR TITLE
refactor: switch to typescript ;)

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by revolunet** [comment]
Possible to move thé build/release into a "when: optional" gitlab step?

**Comment by douglasduteil** [comment]
Possible. 
But it will restrict the number of person allowed to release

**Comment by douglasduteil** [comment]
I would love to move it to GitHub Ci Actions but... I can't find how to make an option build

**Comment by douglasduteil** [comment]
:up: @revolunet ;)

**Comment by revolunet** [comment]
this broke the latest 1.0.2 release; built files are not included in the npm tarball due to TS compilation and package.files. 

@douglasduteil can you have a look please 🙏

**Pull request merged**
